name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal

  doxygen:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build docs
      uses: mattnotmitt/doxygen-action@v1
      with:
        doxyfile-path: 'doxygen_user_manual.conf'

    - name: Transfer docs to runner
      run: sudo chown -R runner user_manual

    - name: Copy images
      run: |
        ls -la ./user_manual/html
        whoami
        mkdir -p user_manual/html/images
        cp -ru images user_manual/html/

    - name: Deploy to github pages
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: pages
        folder: user_manual/html

